Revert sbt version upgrade
For some reason, using sbt 1.4.6 causes compilation errors in
the mimaReportBinaryIssues command.
```
[error] java.lang.NoSuchMethodError:
com.typesafe.tools.mima.core.Settings.allSettings()Lscala/collection/mutable/HashSet;
```

Sorry, I do not have time to track down now, use prior art.